"""
SupportFlow AI — Email Service
--------------------------------
Responsibility: Send all outgoing emails via Resend API.

Two types of emails this service sends:
1. AI Response     → reply to customer with resolved answer
2. Escalation      → notify manager + inform customer a human will help

Usage:
    from services.email_service import EmailService
    email_service = EmailService()
    email_service.send_resolution(to="customer@gmail.com", subject="Re: ...", ai_response="...")
    email_service.send_escalation(to="customer@gmail.com", subject="Re: ...", original_body="...")
"""

import resend
import os
from datetime import datetime


# ─── Configuration ──────────────────────────────────────────────────────────────
RESEND_API_KEY  = os.getenv("RESEND_API_KEY")
SUPPORT_EMAIL   = os.getenv("SUPPORT_EMAIL", "support@yourdomain.com")
MANAGER_EMAIL   = os.getenv("MANAGER_EMAIL", "manager@yourdomain.com")

resend.api_key = RESEND_API_KEY


# ─── Email Templates ────────────────────────────────────────────────────────────
def _resolution_template(customer_name: str, ai_response: str) -> str:
    """Clean HTML template for AI-resolved support replies."""
    return f"""
    <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto;">
        <div style="background: #f8f9fa; padding: 20px; border-radius: 8px;">
            <h2 style="color: #2d3748; margin-bottom: 4px;">SupportFlow AI</h2>
            <p style="color: #718096; font-size: 13px; margin-top: 0;">Automated Support Response</p>
        </div>

        <div style="padding: 24px 0;">
            <p style="color: #2d3748;">Hi {customer_name},</p>
            <p style="color: #2d3748;">Thank you for reaching out. Here is our response to your query:</p>

            <div style="background: #edf2f7; border-left: 4px solid #4299e1;
                        padding: 16px; border-radius: 4px; margin: 20px 0;">
                <p style="color: #2d3748; margin: 0; line-height: 1.6;">
                    {ai_response}
                </p>
            </div>

            <p style="color: #718096; font-size: 14px;">
                If you have any further questions, feel free to reply to this email.
            </p>
        </div>

        <div style="border-top: 1px solid #e2e8f0; padding-top: 16px;">
            <p style="color: #a0aec0; font-size: 12px; margin: 0;">
                SupportFlow AI • Automated Support System<br>
                This response was generated by AI. Reply to reach our team.
            </p>
        </div>
    </div>
    """


def _escalation_customer_template(customer_name: str) -> str:
    """Template sent to customer when their ticket is escalated to a human agent."""
    return f"""
    <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto;">
        <div style="background: #fff5f5; padding: 20px; border-radius: 8px;">
            <h2 style="color: #2d3748; margin-bottom: 4px;">SupportFlow AI</h2>
            <p style="color: #718096; font-size: 13px; margin-top: 0;">Support Team</p>
        </div>

        <div style="padding: 24px 0;">
            <p style="color: #2d3748;">Hi {customer_name},</p>

            <p style="color: #2d3748;">
                Thank you for contacting us. We have reviewed your query and determined
                that it requires personal attention from one of our human support agents.
            </p>

            <div style="background: #fff5f5; border-left: 4px solid #fc8181;
                        padding: 16px; border-radius: 4px; margin: 20px 0;">
                <p style="color: #2d3748; margin: 0;">
                    🔔 <strong>Your ticket has been escalated.</strong><br><br>
                    A member of our support team will reach out to you shortly.
                    Please allow up to 24 hours for a response.
                </p>
            </div>

            <p style="color: #718096; font-size: 14px;">
                We apologize for any inconvenience and appreciate your patience.
            </p>
        </div>

        <div style="border-top: 1px solid #e2e8f0; padding-top: 16px;">
            <p style="color: #a0aec0; font-size: 12px; margin: 0;">
                SupportFlow AI • Support Team<br>
                Do not reply to this notification email.
            </p>
        </div>
    </div>
    """


def _escalation_manager_template(
    sender_email: str,
    subject: str,
    original_body: str,
    intent: str,
    priority: str,
    sentiment: str,
    ticket_id: int,
) -> str:
    """Template sent to manager with full ticket details for escalated cases."""
    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    return f"""
    <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto;">
        <div style="background: #2d3748; padding: 20px; border-radius: 8px;">
            <h2 style="color: #ffffff; margin-bottom: 4px;">🚨 Escalation Alert</h2>
            <p style="color: #a0aec0; font-size: 13px; margin-top: 0;">
                SupportFlow AI — Manager Notification
            </p>
        </div>

        <div style="padding: 24px 0;">
            <p style="color: #2d3748;">A customer ticket has been escalated and requires your attention.</p>

            <table style="width: 100%; border-collapse: collapse; margin: 16px 0;">
                <tr style="background: #f7fafc;">
                    <td style="padding: 10px; border: 1px solid #e2e8f0;
                               font-weight: bold; color: #4a5568; width: 140px;">
                        Ticket ID
                    </td>
                    <td style="padding: 10px; border: 1px solid #e2e8f0; color: #2d3748;">
                        #{ticket_id}
                    </td>
                </tr>
                <tr>
                    <td style="padding: 10px; border: 1px solid #e2e8f0;
                               font-weight: bold; color: #4a5568;">
                        Customer Email
                    </td>
                    <td style="padding: 10px; border: 1px solid #e2e8f0; color: #2d3748;">
                        {sender_email}
                    </td>
                </tr>
                <tr style="background: #f7fafc;">
                    <td style="padding: 10px; border: 1px solid #e2e8f0;
                               font-weight: bold; color: #4a5568;">
                        Subject
                    </td>
                    <td style="padding: 10px; border: 1px solid #e2e8f0; color: #2d3748;">
                        {subject}
                    </td>
                </tr>
                <tr>
                    <td style="padding: 10px; border: 1px solid #e2e8f0;
                               font-weight: bold; color: #4a5568;">
                        Intent
                    </td>
                    <td style="padding: 10px; border: 1px solid #e2e8f0; color: #2d3748;">
                        {intent}
                    </td>
                </tr>
                <tr style="background: #f7fafc;">
                    <td style="padding: 10px; border: 1px solid #e2e8f0;
                               font-weight: bold; color: #4a5568;">
                        Priority
                    </td>
                    <td style="padding: 10px; border: 1px solid #e2e8f0;">
                        <span style="background: #fc8181; color: white; padding: 2px 10px;
                                     border-radius: 12px; font-size: 13px;">
                            {priority.upper()}
                        </span>
                    </td>
                </tr>
                <tr>
                    <td style="padding: 10px; border: 1px solid #e2e8f0;
                               font-weight: bold; color: #4a5568;">
                        Sentiment
                    </td>
                    <td style="padding: 10px; border: 1px solid #e2e8f0; color: #2d3748;">
                        {sentiment}
                    </td>
                </tr>
                <tr style="background: #f7fafc;">
                    <td style="padding: 10px; border: 1px solid #e2e8f0;
                               font-weight: bold; color: #4a5568;">
                        Timestamp
                    </td>
                    <td style="padding: 10px; border: 1px solid #e2e8f0; color: #2d3748;">
                        {timestamp}
                    </td>
                </tr>
            </table>

            <p style="color: #4a5568; font-weight: bold; margin-bottom: 8px;">
                Original Customer Message:
            </p>
            <div style="background: #f7fafc; border: 1px solid #e2e8f0;
                        padding: 16px; border-radius: 4px;">
                <p style="color: #2d3748; margin: 0; line-height: 1.6; white-space: pre-wrap;">
                    {original_body}
                </p>
            </div>

            <div style="margin-top: 20px; padding: 12px; background: #ebf8ff;
                        border-radius: 4px; border-left: 4px solid #4299e1;">
                <p style="color: #2b6cb0; margin: 0; font-size: 14px;">
                    📧 Please reply directly to <strong>{sender_email}</strong> to assist this customer.
                </p>
            </div>
        </div>

        <div style="border-top: 1px solid #e2e8f0; padding-top: 16px;">
            <p style="color: #a0aec0; font-size: 12px; margin: 0;">
                SupportFlow AI — Escalation System<br>
                This is an automated manager notification.
            </p>
        </div>
    </div>
    """


# ─── Email Service Class ─────────────────────────────────────────────────────────
class EmailService:
    """
    Handles all outbound email sending for SupportFlow AI.

    Methods:
        send_resolution()  — send AI-generated reply to customer
        send_escalation()  — notify manager + inform customer
    """

    def send_resolution(
        self,
        to: str,
        subject: str,
        ai_response: str,
    ) -> bool:
        """
        Send AI-resolved response back to the customer.

        Args:
            to:           Customer email address
            subject:      Original email subject (will be prefixed with Re:)
            ai_response:  Final response generated by the agent pipeline

        Returns:
            True if sent successfully, False otherwise
        """
        customer_name = to.split("@")[0].capitalize()
        reply_subject = subject if subject.startswith("Re:") else f"Re: {subject}"

        try:
            resend.Emails.send({
                "from":    f"SupportFlow AI <{os.getenv('FROM_EMAIL', 'onboarding@resend.dev')}>",
                "to":      [to],
                "subject": reply_subject,
                "html":    _resolution_template(customer_name, ai_response),
            })
            print(f"✅ Resolution email sent to {to}")
            return True

        except Exception as e:
            print(f"❌ Failed to send resolution email to {to}: {e}")
            return False

    def send_escalation(
        self,
        to: str,
        subject: str,
        original_body: str,
        intent: str = "unknown",
        priority: str = "high",
        sentiment: str = "negative",
        ticket_id: int = 0,
    ) -> bool:
        """
        Send escalation emails — one to customer, one to manager.

        Args:
            to:            Customer email address
            subject:       Original email subject
            original_body: Original customer message
            intent:        Detected intent from Intent Agent
            priority:      Detected priority from Priority Agent
            sentiment:     Detected sentiment from Intent Agent
            ticket_id:     DB ticket ID for reference

        Returns:
            True if both emails sent successfully, False otherwise
        """
        customer_name  = to.split("@")[0].capitalize()
        reply_subject  = subject if subject.startswith("Re:") else f"Re: {subject}"
        manager_subject = f"🚨 Escalation Alert — Ticket #{ticket_id} | {subject}"

        try:
            # Email 1: Inform customer their ticket is escalated
            resend.Emails.send({
                "from":    f"SupportFlow AI <{os.getenv('FROM_EMAIL', 'onboarding@resend.dev')}>",
                "to":      [to],
                "subject": reply_subject,
                "html":    _escalation_customer_template(customer_name),
            })
            print(f"✅ Escalation email sent to customer: {to}")

            # Email 2: Notify manager with full ticket details
            resend.Emails.send({
                "from":    f"SupportFlow AI <{os.getenv('FROM_EMAIL', 'onboarding@resend.dev')}>",
                "to":      [MANAGER_EMAIL],
                "subject": manager_subject,
                "html":    _escalation_manager_template(
                    sender_email=to,
                    subject=subject,
                    original_body=original_body,
                    intent=intent,
                    priority=priority,
                    sentiment=sentiment,
                    ticket_id=ticket_id,
                ),
            })
            print(f"✅ Escalation alert sent to manager: {MANAGER_EMAIL}")
            return True

        except Exception as e:
            print(f"❌ Failed to send escalation emails: {e}")
            return False